require('mappings')
require('colorschemes-config')
require('packer-config')
require('settings')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('nullls-config')
require('vgit-config')

